language: scala
scala:
  - 2.11.6
  - 2.10.5
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mike.limansky@gmail.com
jdk:
  - openjdk7
  - oraclejdk8
script: "sbt clean coverage test"
after_success: "sbt coveralls"
