language: scala
scala:
  - 2.11.4
  - 2.10.4
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mike.limansky@gmail.com
jdk:
  - openjdk7
  - oraclejdk7

# This lead to random fails on uploading.
# script: "sbt coveralls"
