language: scala
scala:
  - 2.11.7
  - 2.10.6
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mike.limansky@gmail.com
jdk:
  - oraclejdk7
  - oraclejdk8
script: "sbt clean coverage test"
after_success: "sbt coveralls"
